### ISSUE TITLE
I have a question ?

### ISSUE THREAD

**Issue by tentran2k1** [DKPlugins/DKTools#2]
all plugin of DK TOOL it working on mobile ?

**Comment by DKPlugins** [comment]
Yes.

**Comment by tentran2k1** [comment]
including the preloader?

**Comment by DKPlugins** [comment]
Yes.

**Comment by tentran2k1** [comment]
i dont think so 
![59D4221F-96F4-42AA-A585-8A77070787C0](https://user-images.githubusercontent.com/30969413/70488861-95906280-1b2c-11ea-9ce0-60195551d6d0.png)

**Comment by DKPlugins** [comment]
Is it IOS ? Which version ?

**Comment by tentran2k1** [comment]
version lasted ( iphone 6s plus ) and browser on pc also

**Comment by DKPlugins** [comment]
I will try to deal with the problem. This may take some time because I do not have Apple products. I will answer when there is any news. Thank you.

**Comment by tentran2k1** [comment]
I tried it on my android using a browser and so did it. On the console it shows that web browser and mobile do not support preloading :(

**Comment by tentran2k1** [comment]
I hope that the preloading function will be supported on mobile, because DK Plugin uses the preload function very well, if possible, please allow preloading of the sound as well.

**Comment by DKPlugins** [comment]
@tentran2k1 Hello. Sorry that so much time has passed. I tried to study the question as much as I could.

I have compiled a demo for a web browser with DKTools version 8.3.0 (currently relevant) and the resource preload function enabled. I asked a friend to visit the site with his iphone 6 plus. He says he managed to start the game.
I also tried logging in through the Safari browser on MacOS via the virtual machine (it seems it was version 12 of the OS). The game also started.

Here is a link to the demo: https://dk-plugins.ru/demo/dktools/www/index.html

Let me know if you managed to log in or not.
If you manage to log in, then check the parameters of the DKTools plugin.
The FileSystem mode parameter should be Nwjs + Stamp for browsers and mobile devices. Also, before exporting a game, you must run it in RPG Maker to update the stamp file. This is described in more detail in the plugin's help.

If you continue to experience this problem, then please send me the minimum demo version of your project (or a link to the site where it is located) to kuznetsovdenis96@mail.com so that I can study the problem.
